{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maubot-data
  labels:
{{ include "maubot.labels" . | indent 4 }}
  annotations:
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: {{ default "longhorn" .Values.persistence.storageClassName }}
{{- end }}